- p4th/ChanghoonLee/prepare.txt
> init : [이창훈] 개인 프로젝트 초기 커밋

- p4th/BokyeongLim/slide_to_push_frontend/lib/api/spring_api.dart
- p4th/BokyeongLim/slide_to_push_frontend/lib/main.dart
- p4th/BokyeongLim/slide_to_push_frontend/lib/pages/sign_in.dart
- p4th/BokyeongLim/slide_to_push_frontend/lib/utility/color.dart
- p4th/BokyeongLim/slide_to_push_frontend/lib/utility/input_validate.dart
- p4th/BokyeongLim/slide_to_push_frontend/lib/utility/size.dart
- p4th/BokyeongLim/slide_to_push_frontend/pubspec.lock
- p4th/BokyeongLim/slide_to_push_frontend/pubspec.yaml
1. 이메일, 패스워드, 메인 버튼 UI 작업
2. 이메일 유효성 검사 (빈값 체크, @와 .을 넣은 형식인지 체크)
3. 패스워드 유효성 검사 (빈값 체크, 특수문자+번호+문자의 형식인지 체크, 8자에서 15자 사이인지 체크)
> feat : [임보경] 로그인 UI 및 스프링 서버에 전달할 API 작성 완료

- p4th/KaramKim/vue/plants_web/package-lock.json
- p4th/KaramKim/vue/plants_web/package.json
- p4th/KaramKim/vue/plants_web/public/index.html
- p4th/KaramKim/vue/plants_web/src/App.vue
- p4th/KaramKim/vue/plants_web/src/components/HelloWorld.vue
- p4th/KaramKim/vue/plants_web/src/main.js
- p4th/KaramKim/vue/plants_web/src/router/index.js
- p4th/KaramKim/vue/plants_web/src/views/AboutView.vue
- p4th/KaramKim/vue/plants_web/src/views/HomeView.vue
- p4th/KaramKim/vue/plants_web/vue.config.js
> init: [김가람] 개인 저장소 초기화 - frontend

- p4th/GeonoJin/bucket_list_frontend/src/components/common/CategoryComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/common/ToolBarComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/common/account/BucketContentComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/common/account/ButtonComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/common/account/TextFieldComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/router/index.js
- p4th/GeonoJin/bucket_list_frontend/src/views/HomeView.vue
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/controller/member/MemberController.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/controller/member/form/MemberSignUpForm.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/entity/member/Authentication.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/entity/member/BasicAuthentication.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/entity/member/MemberInfo.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/entity/member/MemberProfile.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/repository/member/AuthenticationRepository.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/repository/member/MemberRepository.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/MemberService.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/MemberServiceImpl.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/request/MemberSignUpRequest.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/utility/encrypt/EncryptionUtil.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/utility/expection/UnableToGenerateHash.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/utility/password/PasswordHashConverter.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/test/java/com/example/bucket_list_project/service/member/MemberTestCase.java
- 사용자 email 중복 체크 기능
- 회원가입 기능
- 사용자 Entity
- Repository
- Service
- Controller 맵핑
- 회원가입 된 사용자 패스워드 암호화 기능
- 각 항목 기능 테스트
- 메인페이지 컴포넌트 중 버튼, 텍스트 필드 공통 컴포넌트 설계 및 적용
- 메인페이지 컴포넌트별 버킷리스트 나열( 공통 컴포넌트⭕)
> feat: [진건오] 회원가입 관련 로직 구현

- p4th/SoyeonKim/frontend/looklend/package-lock.json
- p4th/SoyeonKim/frontend/looklend/package.json
- p4th/SoyeonKim/frontend/looklend/src/components/account/SignUpForm.vue
- p4th/SoyeonKim/frontend/looklend/src/router/index.js
- p4th/SoyeonKim/frontend/looklend/src/store/actions.js
- p4th/SoyeonKim/frontend/looklend/src/store/getters.js
- p4th/SoyeonKim/frontend/looklend/src/store/index.js
- p4th/SoyeonKim/frontend/looklend/src/store/mutations.js
- p4th/SoyeonKim/frontend/looklend/src/store/states.js
- p4th/SoyeonKim/frontend/looklend/src/views/HomeView.vue
- p4th/SoyeonKim/frontend/looklend/src/views/account/SignUpView.vue
1. 로그인 UI (의존성 분리는 일단 넘어감)
2.이메일 형식검사, 비밀번호 검사
3. 라우터 연결
> init: [김소연] 회원가입 UI

- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/controller/member/MemberController.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/controller/member/request/MemberLoginForm.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/controller/member/request/MemberRegisterForm.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/entity/Authentication/Authentication.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/entity/Authentication/BasicAuthentication.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/entity/member/Member.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/entity/member/MemberProfile.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/repository/member/AuthenticationRepository.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/repository/member/MemberRepository.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/member/MemberService.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/member/MemberServiceImpl.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/member/request/MemberLoginRequest.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/member/request/MemberRegisterRequest.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/security/RedisService.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/security/RedisServiceImpl.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/utility/encrypt/EncryptionUtil.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/utility/encrypt/exception/UnableToGenerateHash.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/utility/password/PasswordHashConverter.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/test/java/com/example/demo/member/MemberTestCase.java
**완료**
☑️ 이메일 중복 체크 시스템 (테스트 O)
☑️ 회원 가입 시스템 (테스트 O)
**이슈**
✅ SQLException : Field 'id' dosen't have a default value Error 
(엔지니어링 위키 - Spring 프레임 워크 이슈 작성 / 해결 완료)
> feat: [조안나] B) 회원 가입 시 입력 받은 정보를 체크하고 DB에 보관하는 시스템 [LOL-E’SPORTS-KOREA2]

- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/controller/member/MemberController.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/controller/member/form/MemberRegisterForm.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/entity/member/Address.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/entity/member/Authentication.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/entity/member/BasicAuthentication.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/entity/member/Member.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/entity/member/MemberProfile.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/repository/member/AuthenticationRepository.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/repository/member/MemberRepository.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/service/member/MemberService.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/service/member/MemberServiceImpl.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/service/member/request/MemberRegisterRequest.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/service/security/RedisService.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/service/security/RedisServiceImpl.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/utility/encrypt/EncryptionUtil.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/utility/exception/UnableToGenerateHash.java
- p4th/SoyeonKim/backend/look_lend_backend/src/main/java/com/example/look_lend_backend/utility/password/PasswordHashConverter.java
- p4th/SoyeonKim/frontend/looklend/package-lock.json
- p4th/SoyeonKim/frontend/looklend/package.json
- p4th/SoyeonKim/frontend/looklend/public/index.html
- p4th/SoyeonKim/frontend/looklend/src/components/account/LoginForm.vue
- p4th/SoyeonKim/frontend/looklend/src/components/account/SignUpForm.vue
- p4th/SoyeonKim/frontend/looklend/src/router/index.js
- p4th/SoyeonKim/frontend/looklend/src/views/HomeView.vue
- p4th/SoyeonKim/frontend/looklend/src/views/account/SignInView.vue
- p4th/SoyeonKim/frontend/looklend/src/views/account/SignUpView.vue
- [v] vue axios 설치
- [v] 회원가입 UI
> feat: [김소연] 회원가입 UI[LOOKLEND2]

- p4th/SeonhoPark/flutter/look_style/lib/api/spring_api.dart
- p4th/SeonhoPark/flutter/look_style/lib/components/route_button.dart
- p4th/SeonhoPark/flutter/look_style/lib/components/sign_in_email_text_form_field.dart
- p4th/SeonhoPark/flutter/look_style/lib/components/sign_in_form_field.dart
- p4th/SeonhoPark/flutter/look_style/lib/components/sign_in_password_text_form_field.dart
- p4th/SeonhoPark/flutter/look_style/lib/main.dart
- p4th/SeonhoPark/flutter/look_style/lib/pages/sign_in_page.dart
- p4th/SeonhoPark/flutter/look_style/lib/utility/validation.dart
내역
- 로그인 UI
- 회원가입 페이지로 이동하는 버튼
- spring에게 로그인 요청하는 api
- 이메일, 비밀번호 유효성 검사
예정
- 회원가입 UI
- 로그인 시스템
- 회원가입 시스템
> feat: [박선호] 로그인 페이지 UI [LOOK-STYLE1]

- p4th/JaeminChoi/flutter/android/app/build.gradle
- p4th/JaeminChoi/flutter/lib/components/app_bar/common_app_bar.dart
- p4th/JaeminChoi/flutter/lib/components/common_app_bar.dart
- p4th/JaeminChoi/flutter/lib/components/common_appbar_drawer.dart
- p4th/JaeminChoi/flutter/lib/pages/splash_screen_page.dart
- p4th/JaeminChoi/flutter/pubspec.lock
- p4th/JaeminChoi/flutter/pubspec.yaml
[state]
1. 기본 적인 appbar Ui 설계
해야 하는 것
1. 로고와 메인 페이지 연결
2. 로그인 상태 값에 따른 다른 UI연결
3. 메뉴 클릭 시 사이드바 설정
> feat: [최재민] 모든 화면 상단에 나타는 Appbar 초기 설계[Leaning-Helper10]

- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/controller/member/MemberController.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/entity/Authentication/Authentication.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/entity/member/Member.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/entity/member/MemberProfile.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/repository/member/MemberProfileRepository.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/repository/member/MemberRepository.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/member/MemberService.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/member/MemberServiceImpl.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/main/java/com/example/demo/service/security/RedisServiceImpl.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/test/java/com/example/demo/DemoApplicationTests.java
- p4th/AnnaJo/lolEsportsKorea_backend/src/test/java/com/example/demo/member/MemberTestCase.java
- p4th/AnnaJo/lolEsportsKorea_frontend/lib/api/authentication/globals_success_check.dart
- p4th/AnnaJo/lolEsportsKorea_frontend/lib/api/authentication/spring_email_validation_api.dart
- p4th/AnnaJo/lolEsportsKorea_frontend/lib/api/authentication/spring_nickname_validation_api.dart
- p4th/AnnaJo/lolEsportsKorea_frontend/lib/api/authentication/spring_sign_in_api.dart
- p4th/AnnaJo/lolEsportsKorea_frontend/lib/api/authentication/spring_sign_up_api.dart
- p4th/AnnaJo/lolEsportsKorea_frontend/lib/pages/authentication/sign_in_page.dart
- p4th/AnnaJo/lolEsportsKorea_frontend/lib/pages/authentication/sign_up_page.dart
- p4th/AnnaJo/lolEsportsKorea_frontend/lib/utility/common_alert_dialog.dart
백로그 [LOL-E’SPORTS-KOREA2] 이슈 건 해결 완료
> feat: [조안나] B) 회원가입시 입력 받은 정보를 체크하고 DB에 보관하는 시스템 [LOL-E’SPORTS-KOREA11]

- p4th/HeejiYun/backend/src/main/java/com/example/backend/controller/member/MemberController.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/entity/member/BasicAuthentication.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/entity/member/Member.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/member/MemberService.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/member/MemberServiceImpl.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/member/request/MemberSignInRequest.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/security/RedisService.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/security/RedisServiceImpl.java
- p4th/HeejiYun/backend/src/test/java/com/example/backend/MemberSignInTestCase.java
- p4th/HeejiYun/frontend/lib/api/spring_member_api.dart
- p4th/HeejiYun/frontend/lib/components/buttons/navigation_button.dart
- p4th/HeejiYun/frontend/lib/components/custom_alert_dialog.dart
- p4th/HeejiYun/frontend/lib/components/sign_up_form.dart
- p4th/HeejiYun/frontend/lib/components/text_form_fields/text_form_field_email.dart
- p4th/HeejiYun/frontend/lib/components/text_form_fields/text_form_field_nickname.dart
- p4th/HeejiYun/frontend/lib/components/text_form_fields/text_form_field_password.dart
- p4th/HeejiYun/frontend/lib/components/text_form_fields/text_form_field_password_check.dart
- p4th/HeejiYun/frontend/lib/main.dart
- p4th/HeejiYun/frontend/lib/pages/sign_up_complete_page.dart
- p4th/HeejiYun/frontend/pubspec.lock
- p4th/HeejiYun/frontend/pubspec.yaml
- 회원가입 요청을 위한 api 구현 완료(login은 임시로 만들어둠)
- 이메일 중복, 닉네임 중복 검사 결과와 회원 가입 완료를 알리는 Alert Dialog 구현 완료
- 로그인 시스템 구현 완료.
> feat: [윤희지] 중복 검사 결과를 사용자에게 알려주는 AlertDialog [HOME-ALONE12]

- p4th/KaramKim/vue/plants_web/src/components/common/CommonMenuBar.vue
- p4th/KaramKim/vue/plants_web/src/views/account/SignInView.vue
**이슈**
로그인 여부에 따라 메뉴바 상단을 변경하는데 새로고침없이 자동적으로 적용하고 싶으나 구현이 어려움.
Notion: https://www.notion.so/eddi-robot-academy/Vue-2cbceb3a98ef41dcb485d649798af4b6?p=a66a740fae95477cad2c686ddeecf8de&pm=s
> issue: [김가람] F) 로그인 여부에 따라 변하는 우측 상단 메뉴바 구현 [PLANTS2]

- p4th/GeonoJin/bucket_list_frontend/src/components/bucketListKind/AllBucketList.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/common/ButtonComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/common/CategoryComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/common/ToolBarComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/header/HeaderComponent.vue
- p4th/GeonoJin/bucket_list_frontend/src/components/mypage/MyPageForm.vue
- p4th/GeonoJin/bucket_list_frontend/src/main.js
- p4th/GeonoJin/bucket_list_frontend/src/router/index.js
- p4th/GeonoJin/bucket_list_frontend/src/store/actions.js
- p4th/GeonoJin/bucket_list_frontend/src/store/mutations.js
- p4th/GeonoJin/bucket_list_frontend/src/views/HomeView.vue
- p4th/GeonoJin/bucket_list_frontend/src/views/member/MyPageView.vue
- p4th/GeonoJin/bucket_list_frontend/src/views/member/SignInView.vue
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/controller/member/account/MemberController.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/controller/member/accountSet/MemberInfoSetController.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/controller/member/form/MemberSignInForm.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/controller/member/form/MemberSignUpForm.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/controller/member/form/ReplaceNicknameForm.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/entity/member/MemberInfo.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/account/MemberService.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/account/MemberServiceImpl.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/accountSet/MemberAccountSetService.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/accountSet/MemberAccountSetServiceImpl.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/request/account/MemberSignInRequest.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/request/account/MemberSignUpRequest.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/main/java/com/example/bucket_list_project/service/member/request/accountSet/ReplaceNicknameRequest.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/test/java/com/example/bucket_list_project/service/member/MemberAccountSetTestCase.java
- p4th/GeonoJin/bucket_list_project/bucket_list_project/src/test/java/com/example/bucket_list_project/service/member/MemberTestCase.java
- 지난번 로그인 후 새로고침해도 로그인 상태가 유지되지 않았던 이슈를 해결하였는데, 
알 수 없는 이유로 제대로 해결되지 않아 다시 코드 수정하여 이슈 해결
- 닉네임 수정
- 로그인 한 사용자의 닉네임을 수정할 수 있는 페이지 설계
- 변경된 닉네임을 db에 저장하는 로직 구현
> feat: [진건오] 로그인 상태 유지 [BUCKET-LIST12]

- p4th/YeongyeongLee/frontend/public/index.html
- p4th/YeongyeongLee/frontend/src/App.vue
- p4th/YeongyeongLee/frontend/src/components/account/SignUpForm.vue
- p4th/YeongyeongLee/frontend/src/components/common/button/MemberButton.vue
- p4th/YeongyeongLee/frontend/src/components/common/button/PostWriteButton.vue
- p4th/YeongyeongLee/frontend/src/components/common/post/PostWriteForm.vue
- p4th/YeongyeongLee/frontend/src/store/index.js
- p4th/YeongyeongLee/frontend/src/views/HomeView.vue
- p4th/YeongyeongLee/frontend/src/views/MainPage.vue
- p4th/YeongyeongLee/frontend/src/views/country/AfricaBoardView.vue
- p4th/YeongyeongLee/frontend/src/views/country/AsiaBoardView.vue
- p4th/YeongyeongLee/frontend/src/views/country/EuropeBoardView.vue
- p4th/YeongyeongLee/frontend/src/views/country/KoreanBoardView.vue
- p4th/YeongyeongLee/frontend/src/views/country/NorthAmericaBoardView.vue
- p4th/YeongyeongLee/frontend/src/views/country/OceaniaBoardView.vue
- p4th/YeongyeongLee/frontend/src/views/country/SouthAmericaBoardView.vue
- p4th/YeongyeongLee/frontend/src/views/main/MemberButtonView.vue
- p4th/YeongyeongLee/frontend/src/views/main/account/SignUpView.vue
> feat: [이연경] 회원가입 시스템 구현 [TRIP-COMMUNITY5]

- p4th/HeejiYun/backend/src/main/java/com/example/backend/controller/board/BoardController.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/entity/board/Board.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/entity/board/BoardCategory.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/entity/member/Member.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/repository/BoardCategoryRepository.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/repository/BoardRepository.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/BoardService.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/BoardServiceImpl.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/request/BoardModifyRequest.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/request/BoardRegisterRequest.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/request/BoardRequest.java
- p4th/HeejiYun/backend/src/test/java/com/example/backend/BoardRegisterTest.java
- p4th/HeejiYun/backend/src/test/java/com/example/backend/BoardTest.java
> feat: [윤희지] board, board category entity, repository 구현 중 [HOME-ALONE5]

- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/components/toolbar/ToolbarForm.vue
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/components/topMenubar/TopMenuForm.vue
완료
- 마이페이지, 로그아웃 모달창 UI 구현 (기능은 추후에)
- 메뉴바 드롭다운 UI구현 완료
예정
- 각각의 게시판 구현
> 로그인 상태에서 보여지는 마이페이지, 버튼 모달창 UI 구현 및 메뉴바 드롭다운 UI  구현

- p4th/SeonhoPark/flutter/look_style/lib/components/signIn/sign_in_form_field.dart
- p4th/SeonhoPark/flutter/look_style/lib/pages/main_page.dart
- p4th/SeonhoPark/flutter/look_style/lib/pages/sign_in_page.dart
AppBar와 BottomNavigationBar 틀만 잡아놓은 상태
> feat: [박선호] 로그인 후 연결되는 메인페이지 UI [LOOK-STYLE5]

- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/controller/BoardController.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/controller/form/BoardModifyForm.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/controller/form/BoardWriteForm.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/entity/CommunityBoard.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/entity/ReadUsMember.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/service/BoardService.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/service/BoardServiceImpl.java
- p4th/ChaeseonHan/readus_backend/src/test/java/kr/eddi/demo/BoardServiceTestCase.java
- p4th/ChaeseonHan/readus_frontend/src/components/Board/BoardModifyForm.vue
- p4th/ChaeseonHan/readus_frontend/src/components/Board/BoardReadForm.vue
- p4th/ChaeseonHan/readus_frontend/src/router/index.js
- p4th/ChaeseonHan/readus_frontend/src/store/actions.js
- p4th/ChaeseonHan/readus_frontend/src/views/routerView/community/Board/BoardModifyView.vue
- p4th/ChaeseonHan/readus_frontend/src/views/routerView/community/Board/BoardReadView.vue
1. 게시글 수정 기능
2. 게시글 삭제 기능
3. 해당 ui 및 spring에 대한 요청
구현 완료 및 자잘한 수정
> feat. [한채선] 프론트에서 특정 번호의 게시글 삭제 요청시 이를 처리 및 성공 여부를 프론트로 돌려주는 시스템 구현 완료 [READUS-31]

- p4th/HeejiYun/backend/src/main/java/com/example/backend/controller/board/BoardController.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/repository/BoardRepository.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/BoardService.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/BoardServiceImpl.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/response/BoardResponse.java
- p4th/HeejiYun/frontend/lib/api/board.dart
- p4th/HeejiYun/frontend/lib/api/spring_board_api.dart
- p4th/HeejiYun/frontend/lib/components/custom_app_bar.dart
- p4th/HeejiYun/frontend/lib/components/custom_drawer.dart
- p4th/HeejiYun/frontend/lib/components/forms/BoardListView.dart
- p4th/HeejiYun/frontend/lib/main.dart
- p4th/HeejiYun/frontend/lib/pages/board_list_page_ask.dart
- p4th/HeejiYun/frontend/lib/pages/board_list_page_free.dart
- p4th/HeejiYun/frontend/lib/pages/board_list_page_recipe.dart
- p4th/HeejiYun/frontend/lib/pages/board_list_page_stls.dart
- p4th/HeejiYun/frontend/lib/pages/home_page.dart
- p4th/HeejiYun/frontend/lib/utility/board_list_provider.dart
- p4th/HeejiYun/frontend/lib/utility/http_uri.dart
- p4th/HeejiYun/frontend/lib/utility/main_color.dart
- p4th/HeejiYun/frontend/lib/utility/provider_test.dart
- p4th/HeejiYun/frontend/pubspec.lock
- p4th/HeejiYun/frontend/pubspec.yaml
provider를 이용해 spring respose를 받아오려 시도했는데 에러 발생
Error: Could not find the correct Provider<ProviderTest> above this BoardListPageStls Widget
> issue : [윤희지] provider not found exception [HOME-ALONE20]

- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/controller/CommentController.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/controller/MemberController.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/controller/form/CommentModifyForm.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/controller/form/CommentToBoardForm.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/entity/BoardComment.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/entity/CommunityBoard.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/entity/ReadUsMember.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/repository/CommentRepository.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/service/BoardServiceImpl.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/service/CommentService.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/service/CommentServiceImpl.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/service/MemberServiceImpl.java
- p4th/ChaeseonHan/readus_backend/src/main/java/kr/eddi/demo/service/request/CommentWriteToBoardRequest.java
- p4th/ChaeseonHan/readus_backend/src/test/java/kr/eddi/demo/CommentServiceTestCase.java
- p4th/ChaeseonHan/readus_frontend/package-lock.json
- p4th/ChaeseonHan/readus_frontend/package.json
- p4th/ChaeseonHan/readus_frontend/src/components/Board/BoardReadForm.vue
- p4th/ChaeseonHan/readus_frontend/src/components/Board/CommentDetailForm.vue
- p4th/ChaeseonHan/readus_frontend/src/components/Board/CommentListForm.vue
- p4th/ChaeseonHan/readus_frontend/src/components/Board/CommentWriteForm.vue
- p4th/ChaeseonHan/readus_frontend/src/components/Header/MemberMenuComponent.vue
- p4th/ChaeseonHan/readus_frontend/src/store/actions.js
- p4th/ChaeseonHan/readus_frontend/src/store/index.js
1. 댓글 entity 추가 및 다른 엔티티와 매핑
2. 댓글 작성 기능 및 ui 구현
3. 댓글 수정 기능 및 ui 구현
4. 게시글 상세보기에서 댓글 list ui 추가
5. 댓글 삭제 기능  및 ui와 연결 완료
> feat. [한채선] 댓글 삭제 기능까지 구현 완료 [READUS-37]

- p4th/HeejiYun/frontend/lib/api/spring_board_api.dart
- p4th/HeejiYun/frontend/lib/components/buttons/category_drop-down_btn.dart
- p4th/HeejiYun/frontend/lib/components/custom_drawer.dart
- p4th/HeejiYun/frontend/lib/components/custom_rich_text.dart
- p4th/HeejiYun/frontend/lib/components/forms/board_register_form.dart
- p4th/HeejiYun/frontend/lib/components/text_form_fields/text_form_field_for_board.dart
- p4th/HeejiYun/frontend/lib/main.dart
- p4th/HeejiYun/frontend/lib/pages/boards/board_list_page_notice.dart
- p4th/HeejiYun/frontend/lib/utility/board_list_provider.dart
- p4th/HeejiYun/frontend/lib/utility/category_provider.dart
게시물 등록이 동작하는 것 확인. 아직 로그인 상태인 사용자의 정보를 받아오는 부분을 만들지 않아서 임의의 값을 넣어 동작을 확인한 상태. 사용자 정보 받아오는 기능을 만들고 수정할 예정.
> feat: [윤희지] 게시물 작성 페이지 UI [HOME-ALONE19]

- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/components/boards/buyBoard/baram/BuyBaramList.vue
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/components/boards/buyBoard/baram/BuyBaramModifyForm.vue
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/components/boards/buyBoard/baram/BuyBaramRead.vue
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/components/boards/buyBoard/baram/BuyBaramRegisterForm.vue
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/components/topMenubar/TopMenuForm.vue
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/store/states.js
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/views/account/SignInView.vue
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/views/boards/buyBoard/baram/BuyBaramListView.vue
- p4th/ChanghoonLee/trade_frontend/vue/frontend/src/views/boards/buyBoard/baram/BuyBaramReadView.vue
> 게시물 CRUD 스타일 수정 및 로그인 여부에 따른 기능 수정

- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/BoardServiceImpl.java
- p4th/HeejiYun/backend/src/main/java/com/example/backend/service/board/response/BoardResponse.java
- p4th/HeejiYun/frontend/lib/api/board.dart
- p4th/HeejiYun/frontend/lib/api/spring_board_api.dart
- p4th/HeejiYun/frontend/lib/components/custom_drawer.dart
- p4th/HeejiYun/frontend/lib/components/forms/board_list_view.dart
- p4th/HeejiYun/frontend/lib/components/forms/board_modify_form.dart
- p4th/HeejiYun/frontend/lib/pages/boards/board_detail_page.dart
- p4th/HeejiYun/frontend/lib/pages/boards/board_list_page_ask.dart
- p4th/HeejiYun/frontend/lib/pages/boards/board_list_page_free.dart
- p4th/HeejiYun/frontend/lib/pages/boards/board_list_page_recipe.dart
게시판 CRUD UI가 Spring과 잘 통신하고 동작하는 것 확인 완료.
사용자가 로그인 상태인지 확인하는 기능, 로그인 중인 사용자의 정보(이메일, 닉네임)를 spring에 요청해서 받아오는 기능이 미구현 상태이므로 이 기능들이 구현 완료되면 게시판 CRUD 관련 UI에 기능을 추가하며 코드를 수정할 예정임.
> feat: [윤희지] 게시물 편집 페이지 UI [HOME-ALONE27]
